project_id = "wbtpefszwywgmnqssrgx"

[functions.alert-ingest]
verify_jwt = false

[functions.alert-escalation-worker]
verify_jwt = false

[functions.flowpulse-reactor]
verify_jwt = false

[functions.zabbix-proxy]
verify_jwt = false

[functions.zabbix-connections]
verify_jwt = false

[functions.zabbix-poller]
verify_jwt = false

[functions.rms-fueling]
verify_jwt = false
